### ISSUE TITLE
NPE using ProcessCoverageInMemProcessEngineConfiguration for Unit Test

### ISSUE THREAD

**Issue by zene22** [camunda/camunda-bpm-process-test-coverage#41] opened 2018-08-22 12:14 UTC
I tried to use the test coverage (https://github.com/camunda/camunda-bpm-process-test-coverage 3) with a simple Workflow just using a link event (see https://docs.camunda.org/manual/7.8/reference/bpmn20/events/link-events/#camunda-extensions 2). The unit tests throws a NPE at

at org.camunda.bpm.extension.process_test_coverage.listeners.IntermediateEventExecutionListener.notify(IntermediateEventExecutionListener.java:32)

With using StandaloneInMemProcessEngineConfiguration instead of ProcessCoverageInMemProcessEngineConfiguration in camunda.cfg.xml the test works fine.

The initialization of PathCoverageParseListener#coverageTestRunState is not done for some reason.

I checked in a small testproject to reproduce this behaviour: 
https://github.com/zene22/camunda_npe_problem_link_events.git

**Comment by akamble-incomm** [comment] 2019-08-06 16:23
Hey zene22, were you able to figure this out? Running into the same problem when I reach a timer event in my workflow.

**Comment by lfkimura** [comment] 2020-02-27 19:26
Got the same issue @zene22, Did you find a solution for these problem ?

**Comment by zene22** [comment] 2020-02-29 08:00
No, sorry, I've no solution for this :(Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Luis Fernando Kimura <notifications@github.com> Datum: 27.02.20  20:26  (GMT+01:00) An: camunda/camunda-bpm-process-test-coverage <camunda-bpm-process-test-coverage@noreply.github.com> Cc: Andreas Furbach <andreas@furbach.info>, Mention <mention@noreply.github.com> Betreff: Re: [camunda/camunda-bpm-process-test-coverage] NPE using ProcessCoverageInMemProcessEngineConfiguration for Unit Test (#41) Got the same issue @zene22, Did you find a solution for these problem ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/camunda/camunda-bpm-process-test-coverage/issues/41?email_source=notifications\u0026email_token=AD6J5A3U7O7UUIG5BKYJNGLRFAHV3A5CNFSM4FQ6E4IKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENFUF6A#issuecomment-592134904",
"url": "https://github.com/camunda/camunda-bpm-process-test-coverage/issues/41?email_source=notifications\u0026email_token=AD6J5A3U7O7UUIG5BKYJNGLRFAHV3A5CNFSM4FQ6E4IKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENFUF6A#issuecomment-592134904",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ivpal** [comment] 2020-08-11 05:14
I have some issue.

**Comment by zambrovski** [comment] 2020-10-19 11:49
Hi,

I reproduced your problem and found the problem. You should configure the coverage rule differently.
I created a fix and pushed it here:  https://github.com/zambrovski/camunda_npe_problem_link_events

I'll close the issue, since it works for me, if the rule is configured correctly.

**Closed by zambrovski** 2020-10-19 11:49 UTC
Labels: bug
